version: "3.8"
services:
  nginx:
    build:
      context: images/nginx
    container_name: m2_nginx
    ports:
      - 80:80
      - 443:443
    volumes_from:
      - php
    volumes:
      - ./app:/var/www/html
      - ./images/nginx/ssl:/etc/ssl
    links:
      - php

  php:
    build:
      context: images/php
    container_name: m2_php
    volumes:
      - ./app:/var/www/html
      - composer:/home/ltucillo/.composer
    links:
      - mysql
    stdin_open: true
    tty: true
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"

  mysql:
    image: percona:5.7
    container_name: m2_mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db-data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    container_name: m2_mailhog
    ports:
      - 1025:1025
      - 8025:8025

  redis:
    image: redis:latest
    container_name: m2_redis
    ports:
      - 6379:6379

  redismin:
    image: redsmin/proxy
    container_name: m2_redismin
    environment:
      REDSMIN_KEY: ${REDISMIN_KEY}
      REDIS_URI: redis://redis:6379

  elk:
    image: magento/magento-cloud-docker-elasticsearch:7.9-1.2.1
    container_name: m2_elk
    ports:
      - 9200:9200
      - 9300:9300
  
  rabbitmq:
    image: rabbitmq:latest
    container_name: m2_rabbitmq
    ports: 
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 25672:25672

volumes:
  db-data:
  composer:


#sysctl -w vm.max_map_count=262144
#bin/magento setup:config:set --cache-backend=redis --cache-backend-redis-server=redis --cache-backend-redis-db=0
#bin/magento setup:config:set --session-save=redis --session-save-redis-host=redis --session-save-redis-db=1