nginx:
    image: nginx:latest
    container_name: nginx_magento2
    ports:
        - 80:80
        - 443:443
    volumes:
        - ../:/var/www/html
        - ./config/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
        - ./config/nginx/conf/magento2.conf:/etc/nginx/magento2.conf
        - ../var/log/nginx:/var/log/nginx
        - ./config/ssl/cert.pem:/etc/nginx/ssl/cert.pem
        - ./config/ssl/cert.key:/etc/nginx/ssl/cert.key
    links:
        - php
php:
    build: php
    container_name: php7
    volumes:
        - ../:/var/www/html
    links:
        - mysql
    stdin_open: true
    tty: true
mysql:
    image: mysql:5.6
    container_name: mysql
    ports:
        - 3306:3306
    volumes:
        - ~/docker-data/mysql56:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=1234qwer
mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"