version: "2"
services:
  nginx:
    build:
      context: images/nginx
      args:
        username: ${USERNAME}
        app_path: ${APP_PATH}
    container_name: m2_nginx
    ports:
      - 80:80
      - 443:443
    volumes_from:
      - php
    volumes:
      - ./images/nginx/conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./images/nginx/conf/includes/:/etc/nginx/includes/
      - ./images/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./images/nginx/conf/ssl/:/etc/nginx/ssl/
      - ../var/log/nginx:/var/log/nginx
    links:
      - php

  php:
    build:
      context: images/php
      args:
        username: ${USERNAME}
        app_path: ${APP_PATH}
    container_name: m2_php
    volumes:
      - magento2v:/var/www/html:nocopy,delegated
      - ~/docker-data/m2_php/composer/:/home/${USERNAME}/.composer/
    links:
      - mysql
    stdin_open: true
    tty: true
    environment:
      XDEBUG_CONFIG: "remote_enabled=1;remote_port=9001;remote_connect_back=1;remote_autostart=1;"
      PHP_XDEBUG_ENABLED: 1
      PHP_IDE_CONFIG: "serverName=Docker"

  mysql:
    image: mysql:5.6
    container_name: m2_mysql
    ports:
      - 3306:3306
    volumes:
      - mysqlv:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=1234qwer
      - MYSQL_DATABASE=magento2

  mailhog:
    image: mailhog/mailhog
    container_name: m2_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  magento2v:
    external: true
  mysqlv:
    external: true